name = "openglada_images"
description = "Image loading library for OpenGLAda"
version = "0.9.0"
website = "http://flyx.github.io/OpenGLAda/"
authors = ["Felix Krause"]
licenses = "MIT"
maintainers = ["Felix Krause <contact@flyx.org>"]
maintainers-logins = ["flyx"]
project-files = ["opengl-images.gpr"]
tags = ["opengl", "rendering", "graphics"]

[[depends-on]]
gid = "^9.0.0"
openglada = "~0.9.0"
